// Documentation Generator: produces SELF_MODEL.md at the workspace root from
// the live self-model, capability map and installed modules. The generated
// document is picked up by the next introspection (docs scan) automatically.

import fs from "fs";
import path from "path";
import { db, capabilitiesTable, modulesTable } from "@workspace/db";
import { scanSelf } from "./selfAwareness";
import { workspaceRoot } from "./codeScan";
import { audit } from "./audit";

export interface DocsGenerated {
  file: string;
  bytes: number;
  sections: string[];
  generatedAt: string;
}

export async function generateSelfModelDocs(): Promise<DocsGenerated> {
  const model = scanSelf();
  const capabilities = await db.select().from(capabilitiesTable).orderBy(capabilitiesTable.id);
  const modules = await db.select().from(modulesTable).orderBy(modulesTable.id);
  const generatedAt = new Date().toISOString();

  const sections = ["Overview", "Capabilities", "Endpoints", "Database Tables", "Installed Modules", "Dependencies"];
  const lines: string[] = [
    "# Forge Self-Model",
    "",
    `> Generated by Forge's Documentation Generator on ${generatedAt}. Do not edit by hand; regenerate via POST /api/docs/generate.`,
    "",
    "## Overview",
    "",
    `- Source files: ${model.sourceFiles.length}`,
    `- API endpoints: ${model.endpoints.length}`,
    `- Database tables: ${model.dbTables.length}`,
    `- Documentation files: ${model.docs.length}`,
    `- Runtime dependencies: ${model.dependencies.length}`,
    "",
    "## Capabilities",
    "",
    "| Key | Name | Status | Maturity |",
    "|---|---|---|---|",
    ...capabilities.map((c) => `| ${c.key} | ${c.name} | ${c.status} | ${c.maturity} |`),
    "",
    "## Endpoints",
    "",
    ...model.endpoints.map((e) => `- \`${e.method} ${e.path}\``),
    "",
    "## Database Tables",
    "",
    ...model.dbTables.map((t) => `- \`${t.table}\` (${t.file})`),
    "",
    "## Installed Modules",
    "",
    ...(modules.length > 0
      ? modules.map((m) => `- ${m.name} v${m.version} — ${m.type}, ${m.installStatus}${m.active ? ", active" : ""}`)
      : ["(none)"]),
    "",
    "## Dependencies",
    "",
    ...model.dependencies.map((d) => `- ${d}`),
    "",
  ];

  const content = lines.join("\n");
  const file = "SELF_MODEL.md";
  fs.writeFileSync(path.join(workspaceRoot, file), content, "utf8");

  const result: DocsGenerated = { file, bytes: Buffer.byteLength(content, "utf8"), sections, generatedAt };
  await audit({
    actor: "docs-generator",
    action: "docs_generated",
    targetType: "doc",
    details: `${file}: ${result.bytes} bytes, sections: ${sections.join(", ")}`,
  });
  return result;
}
